steps:
  - id: "Build"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: sh
    args:
      [
        "/workspace/backend/cloudbuild/scripts/build.sh",
        "$PROJECT_ID",
        "${_PROJECT_SERVICE}",
        "$COMMIT_SHA",
      ]
  - id: "Deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: sh
    args:
      [
        "/workspace/backend/cloudbuild/scripts/deploy.sh",
        "${_PROJECT_SERVICE}",
        "$PROJECT_ID",
        "$LOCATION",
        "$COMMIT_SHA",
        "${_DATABASE_URL}",
      ]
images:
  - "gcr.io/$PROJECT_ID/${_PROJECT_SERVICE}:$COMMIT_SHA"
timeout: 1000s
